---
# tasks file for flight-api
- name: apt-update
  apt:
   update_cache: yes

- name: Install Docker
  apt:
   name: docker.io
   state: present


- name: Install docker-compose
  get_url: 
   url : https://github.com/docker/compose/releases/download/1.25.1-rc1/docker-compose-Linux-x86_64
   dest: /usr/local/bin/docker-compose
   mode: 'u+x,g+x'

- name: Create new directory
  file:
   path: /home/flight-api
   state: directory

- name: Create new directory target
  file:
   path: /home/flight-api/target
   state: directory

- name: Copy war file
  copy:
   src: /root/.jenkins/workspace/Flight-Project-API/target/airline-0.0.1-SNAPSHOT.jar
   dest: /home/flight-api/target

- name: Copy Dockerfile
  copy:
   src: /root/.jenkins/workspace/Flight-Project-API/Dockerfile
   dest: /home/flight-api/

- name: Copy Docker-Compose
  copy:
   src: /root/.jenkins/workspace/spring_flight_api/Dockerfile
   dest: /home/flight-api/

- name: Run Docker Compose
  command: chdir=/home/flight-api/ docker-compose up -d

